version: '3.3'
services:
  nginx:
    image: arm64v8/nginx
    container_name: proxy
    restart: unless-stopped
    volumes:
      - nginx_conf:/etc/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 443:443
      - 10000-10019:10000-10019

volumes:
  nginx_conf:
