version: '3.3'
services:
  nginx:
    image: arm64v8/nginx
    container_name: proxy
    volumes:
      - nginx_conf:/etc/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 443:443

volumes:
  nginx_conf:
