version: '3.3'
services:
  nginx:
    image: arm64v8/nginx
    container_name: proxy
    restart: unless-stopped
    volumes:
      - nginx_conf:/etc/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 10000-10013:10000-10013

volumes:
  nginx_conf:
